/**
 * Map an original `/images/foo.png` path to its small recycle-page WebP copy in
 * `/images/recycle/foo.webp` (generated by `npm run images:recycle`). Anything that
 * isn't an `/images/` path (or is empty) is returned unchanged.
 */
export function recycleSrc(src?: string): string | undefined {
  if (!src || !src.startsWith("/images/")) return src;
  const base = src.slice("/images/".length).replace(/\.(png|webp|jpe?g)$/i, ".webp");
  return `/images/recycle/${base}`;
}
