/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkinningRouteImport } from './routes/skinning'
import { Route as ShopsRouteImport } from './routes/shops'
import { Route as SalvagingRouteImport } from './routes/salvaging'
import { Route as RecyclingRouteImport } from './routes/recycling'
import { Route as RaidRouteImport } from './routes/raid'
import { Route as GiantExcavatorRouteImport } from './routes/giant-excavator'
import { Route as GeneticsRouteImport } from './routes/genetics'
import { Route as FurnaceRouteImport } from './routes/furnace'
import { Route as DecayRouteImport } from './routes/decay'
import { Route as CupboardRouteImport } from './routes/cupboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as CalculatorsIndexRouteImport } from './routes/calculators.index'
import { Route as GuidesMonumentsRouteImport } from './routes/guides.monuments'
import { Route as GuidesFarmingRouteImport } from './routes/guides.farming'
import { Route as GuidesBaseBuildingRouteImport } from './routes/guides.base-building'

const SkinningRoute = SkinningRouteImport.update({
  id: '/skinning',
  path: '/skinning',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsRoute = ShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const SalvagingRoute = SalvagingRouteImport.update({
  id: '/salvaging',
  path: '/salvaging',
  getParentRoute: () => rootRouteImport,
} as any)
const RecyclingRoute = RecyclingRouteImport.update({
  id: '/recycling',
  path: '/recycling',
  getParentRoute: () => rootRouteImport,
} as any)
const RaidRoute = RaidRouteImport.update({
  id: '/raid',
  path: '/raid',
  getParentRoute: () => rootRouteImport,
} as any)
const GiantExcavatorRoute = GiantExcavatorRouteImport.update({
  id: '/giant-excavator',
  path: '/giant-excavator',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneticsRoute = GeneticsRouteImport.update({
  id: '/genetics',
  path: '/genetics',
  getParentRoute: () => rootRouteImport,
} as any)
const FurnaceRoute = FurnaceRouteImport.update({
  id: '/furnace',
  path: '/furnace',
  getParentRoute: () => rootRouteImport,
} as any)
const DecayRoute = DecayRouteImport.update({
  id: '/decay',
  path: '/decay',
  getParentRoute: () => rootRouteImport,
} as any)
const CupboardRoute = CupboardRouteImport.update({
  id: '/cupboard',
  path: '/cupboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsIndexRoute = CalculatorsIndexRouteImport.update({
  id: '/calculators/',
  path: '/calculators/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesMonumentsRoute = GuidesMonumentsRouteImport.update({
  id: '/guides/monuments',
  path: '/guides/monuments',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesFarmingRoute = GuidesFarmingRouteImport.update({
  id: '/guides/farming',
  path: '/guides/farming',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesBaseBuildingRoute = GuidesBaseBuildingRouteImport.update({
  id: '/guides/base-building',
  path: '/guides/base-building',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cupboard': typeof CupboardRoute
  '/decay': typeof DecayRoute
  '/furnace': typeof FurnaceRoute
  '/genetics': typeof GeneticsRoute
  '/giant-excavator': typeof GiantExcavatorRoute
  '/raid': typeof RaidRoute
  '/recycling': typeof RecyclingRoute
  '/salvaging': typeof SalvagingRoute
  '/shops': typeof ShopsRoute
  '/skinning': typeof SkinningRoute
  '/guides/base-building': typeof GuidesBaseBuildingRoute
  '/guides/farming': typeof GuidesFarmingRoute
  '/guides/monuments': typeof GuidesMonumentsRoute
  '/calculators/': typeof CalculatorsIndexRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cupboard': typeof CupboardRoute
  '/decay': typeof DecayRoute
  '/furnace': typeof FurnaceRoute
  '/genetics': typeof GeneticsRoute
  '/giant-excavator': typeof GiantExcavatorRoute
  '/raid': typeof RaidRoute
  '/recycling': typeof RecyclingRoute
  '/salvaging': typeof SalvagingRoute
  '/shops': typeof ShopsRoute
  '/skinning': typeof SkinningRoute
  '/guides/base-building': typeof GuidesBaseBuildingRoute
  '/guides/farming': typeof GuidesFarmingRoute
  '/guides/monuments': typeof GuidesMonumentsRoute
  '/calculators': typeof CalculatorsIndexRoute
  '/guides': typeof GuidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cupboard': typeof CupboardRoute
  '/decay': typeof DecayRoute
  '/furnace': typeof FurnaceRoute
  '/genetics': typeof GeneticsRoute
  '/giant-excavator': typeof GiantExcavatorRoute
  '/raid': typeof RaidRoute
  '/recycling': typeof RecyclingRoute
  '/salvaging': typeof SalvagingRoute
  '/shops': typeof ShopsRoute
  '/skinning': typeof SkinningRoute
  '/guides/base-building': typeof GuidesBaseBuildingRoute
  '/guides/farming': typeof GuidesFarmingRoute
  '/guides/monuments': typeof GuidesMonumentsRoute
  '/calculators/': typeof CalculatorsIndexRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cupboard'
    | '/decay'
    | '/furnace'
    | '/genetics'
    | '/giant-excavator'
    | '/raid'
    | '/recycling'
    | '/salvaging'
    | '/shops'
    | '/skinning'
    | '/guides/base-building'
    | '/guides/farming'
    | '/guides/monuments'
    | '/calculators/'
    | '/guides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cupboard'
    | '/decay'
    | '/furnace'
    | '/genetics'
    | '/giant-excavator'
    | '/raid'
    | '/recycling'
    | '/salvaging'
    | '/shops'
    | '/skinning'
    | '/guides/base-building'
    | '/guides/farming'
    | '/guides/monuments'
    | '/calculators'
    | '/guides'
  id:
    | '__root__'
    | '/'
    | '/cupboard'
    | '/decay'
    | '/furnace'
    | '/genetics'
    | '/giant-excavator'
    | '/raid'
    | '/recycling'
    | '/salvaging'
    | '/shops'
    | '/skinning'
    | '/guides/base-building'
    | '/guides/farming'
    | '/guides/monuments'
    | '/calculators/'
    | '/guides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CupboardRoute: typeof CupboardRoute
  DecayRoute: typeof DecayRoute
  FurnaceRoute: typeof FurnaceRoute
  GeneticsRoute: typeof GeneticsRoute
  GiantExcavatorRoute: typeof GiantExcavatorRoute
  RaidRoute: typeof RaidRoute
  RecyclingRoute: typeof RecyclingRoute
  SalvagingRoute: typeof SalvagingRoute
  ShopsRoute: typeof ShopsRoute
  SkinningRoute: typeof SkinningRoute
  GuidesBaseBuildingRoute: typeof GuidesBaseBuildingRoute
  GuidesFarmingRoute: typeof GuidesFarmingRoute
  GuidesMonumentsRoute: typeof GuidesMonumentsRoute
  CalculatorsIndexRoute: typeof CalculatorsIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skinning': {
      id: '/skinning'
      path: '/skinning'
      fullPath: '/skinning'
      preLoaderRoute: typeof SkinningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops': {
      id: '/shops'
      path: '/shops'
      fullPath: '/shops'
      preLoaderRoute: typeof ShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salvaging': {
      id: '/salvaging'
      path: '/salvaging'
      fullPath: '/salvaging'
      preLoaderRoute: typeof SalvagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recycling': {
      id: '/recycling'
      path: '/recycling'
      fullPath: '/recycling'
      preLoaderRoute: typeof RecyclingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raid': {
      id: '/raid'
      path: '/raid'
      fullPath: '/raid'
      preLoaderRoute: typeof RaidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giant-excavator': {
      id: '/giant-excavator'
      path: '/giant-excavator'
      fullPath: '/giant-excavator'
      preLoaderRoute: typeof GiantExcavatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genetics': {
      id: '/genetics'
      path: '/genetics'
      fullPath: '/genetics'
      preLoaderRoute: typeof GeneticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/furnace': {
      id: '/furnace'
      path: '/furnace'
      fullPath: '/furnace'
      preLoaderRoute: typeof FurnaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decay': {
      id: '/decay'
      path: '/decay'
      fullPath: '/decay'
      preLoaderRoute: typeof DecayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cupboard': {
      id: '/cupboard'
      path: '/cupboard'
      fullPath: '/cupboard'
      preLoaderRoute: typeof CupboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/': {
      id: '/calculators/'
      path: '/calculators'
      fullPath: '/calculators/'
      preLoaderRoute: typeof CalculatorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/monuments': {
      id: '/guides/monuments'
      path: '/guides/monuments'
      fullPath: '/guides/monuments'
      preLoaderRoute: typeof GuidesMonumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/farming': {
      id: '/guides/farming'
      path: '/guides/farming'
      fullPath: '/guides/farming'
      preLoaderRoute: typeof GuidesFarmingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/base-building': {
      id: '/guides/base-building'
      path: '/guides/base-building'
      fullPath: '/guides/base-building'
      preLoaderRoute: typeof GuidesBaseBuildingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CupboardRoute: CupboardRoute,
  DecayRoute: DecayRoute,
  FurnaceRoute: FurnaceRoute,
  GeneticsRoute: GeneticsRoute,
  GiantExcavatorRoute: GiantExcavatorRoute,
  RaidRoute: RaidRoute,
  RecyclingRoute: RecyclingRoute,
  SalvagingRoute: SalvagingRoute,
  ShopsRoute: ShopsRoute,
  SkinningRoute: SkinningRoute,
  GuidesBaseBuildingRoute: GuidesBaseBuildingRoute,
  GuidesFarmingRoute: GuidesFarmingRoute,
  GuidesMonumentsRoute: GuidesMonumentsRoute,
  CalculatorsIndexRoute: CalculatorsIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
